// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'en'.
 * Edit translations in place; re-run extract (with --merge) to fill new gaps.
 * Do not hand-edit the structure — only the leaf string values.
 * Merge only fills gaps: correcting a source label/description does not
 * push the correction into a leaf here that already holds a translation —
 * a present-but-stale string is not a gap, so it is left as-is. Re-translate
 * it by hand when its source changes; nothing here or in `os i18n check`
 * tells a leaf a translator updated on purpose from one nobody has looked
 * at since the source moved.
 */

import type { TranslationData } from '@objectstack/spec/system';

export const enTranslations: TranslationData = {
  objects: {
    kpi_adjustment: {
      label: "Data Adjustment",
      pluralLabel: "Data Adjustment",
      description: "A request to correct a submitted actual value (source data) or score (computed result).",
      fields: {
        name: {
          label: "Adjustment No."
        },
        sheet: {
          label: "Entry Sheet"
        },
        plan: {
          label: "Assessment Plan"
        },
        subject: {
          label: "Subject"
        },
        line: {
          label: "Adjusted Entry Line"
        },
        adjust_type: {
          label: "Adjustment Type",
          options: {
            source: "Source Data (Actual Value)",
            result: "Computed Result (Score)"
          }
        },
        old_value: {
          label: "Value Before"
        },
        new_value: {
          label: "Value After"
        },
        reason: {
          label: "Adjustment Reason"
        },
        status: {
          label: "Status",
          options: {
            draft: "Draft",
            submitted: "Awaiting Approval",
            approved: "Approved",
            rejected: "Declined"
          }
        },
        requested_by: {
          label: "Requested By"
        },
        decided_by: {
          label: "Approved By"
        },
        decided_at: {
          label: "Approved At"
        },
        decision_reason: {
          label: "Approval Comment"
        },
        applied_at: {
          label: "Applied At"
        }
      },
      _actions: {
        kpi_adjustment_approve: {
          label: "Approve & Apply",
          description: "Approving corrects the line and rescores it immediately. Approve?",
          successMessage: "Adjustment approved and applied; the score has been recalculated.",
          params: {
            decision_reason: {
              label: "Approval Comment (optional)"
            }
          }
        },
        kpi_adjustment_reject: {
          label: "Decline",
          successMessage: "Adjustment request declined.",
          params: {
            decision_reason: {
              label: "Decline Reason"
            }
          }
        },
        kpi_adjustment_submit: {
          label: "Submit for Approval",
          successMessage: "Adjustment request submitted; awaiting HR approval."
        }
      },
      _views: {
        default: {
          label: "Data Adjustment"
        },
        pending: {
          label: "Awaiting Approval"
        }
      },
      _sections: {
        request: {
          label: "Adjustment Request"
        }
      }
    },
    kpi_bonus: {
      label: "Bonus & Penalty",
      pluralLabel: "Bonus & Penalty",
      description: "Bonus or penalty points recorded outside the indicator scores.",
      fields: {
        sheet: {
          label: "Entry Sheet"
        },
        title: {
          label: "Item"
        },
        bonus_type: {
          label: "Type",
          options: {
            add: "Bonus",
            deduct: "Penalty"
          }
        },
        points: {
          label: "Points"
        },
        signed_points: {
          label: "Effective Points"
        },
        reason: {
          label: "Basis"
        },
        status: {
          label: "Status",
          options: {
            draft: "Awaiting Approval",
            approved: "Approved",
            rejected: "Declined"
          }
        },
        approved_by: {
          label: "Approved By"
        },
        approved_at: {
          label: "Approved At"
        }
      },
      _actions: {
        kpi_bonus_approve: {
          label: "Approve",
          successMessage: "Bonus/penalty approved and included in the final score."
        },
        kpi_bonus_reject: {
          label: "Decline",
          successMessage: "Bonus/penalty declined."
        }
      },
      _views: {
        default: {
          label: "Bonus & Penalty"
        },
        pending: {
          label: "Awaiting Approval"
        }
      },
      _sections: {
        main: {
          label: "Bonus & Penalty"
        }
      }
    },
    kpi_check_task: {
      label: "Check Task",
      pluralLabel: "Check Task",
      description: "Parallel verification of an entry sheet by each branch: confirm, or raise a dispute.",
      fields: {
        name: {
          label: "Task Name"
        },
        sheet: {
          label: "Entry Sheet"
        },
        plan: {
          label: "Assessment Plan"
        },
        branch: {
          label: "Checking Branch"
        },
        status: {
          label: "Verification Status",
          options: {
            pending: "Awaiting Verification",
            confirmed: "Confirmed",
            disputed: "Disputed"
          }
        },
        comment: {
          label: "Verification Comment"
        },
        decided_by: {
          label: "Checked By"
        },
        decided_at: {
          label: "Checked At"
        }
      },
      _actions: {
        kpi_check_confirm: {
          label: "Confirm as Correct",
          successMessage: "Verified as correct.",
          params: {
            comment: {
              label: "Verification Comment (optional)"
            }
          }
        },
        kpi_check_dispute: {
          label: "Raise Dispute",
          successMessage: "Dispute recorded. Settle it with the reporting department, then confirm.",
          params: {
            comment: {
              label: "Dispute Detail"
            }
          }
        }
      },
      _views: {
        default: {
          label: "All Check Tasks"
        },
        pending: {
          label: "My Verifications"
        },
        disputed: {
          label: "Disputed"
        }
      },
      _sections: {
        main: {
          label: "Check Task"
        }
      }
    },
    kpi_dispute: {
      label: "Indicator Dispute",
      pluralLabel: "Indicator Dispute",
      description: "A dispute raised by a branch against an indicator assignment, and how the business department resolved it.",
      fields: {
        name: {
          label: "Dispute No."
        },
        plan_indicator: {
          label: "Disputed Assignment"
        },
        raised_unit: {
          label: "Raised By Unit"
        },
        raised_by: {
          label: "Raised By"
        },
        reason: {
          label: "Dispute Reason"
        },
        status: {
          label: "Status",
          options: {
            open: "Open",
            accepted: "Upheld",
            rejected: "Rejected"
          }
        },
        resolution: {
          label: "Resolution"
        },
        resolved_by: {
          label: "Resolved By"
        },
        resolved_at: {
          label: "Resolved At"
        }
      },
      _actions: {
        kpi_dispute_accept: {
          label: "Uphold",
          successMessage: "Dispute upheld — adjust the indicator assignment accordingly.",
          params: {
            resolution: {
              label: "Resolution"
            }
          }
        },
        kpi_dispute_reject: {
          label: "Dismiss",
          successMessage: "Dispute closed as dismissed.",
          params: {
            resolution: {
              label: "Resolution"
            }
          }
        }
      },
      _views: {
        default: {
          label: "All Disputes"
        },
        open: {
          label: "Open"
        }
      },
      _sections: {
        raise: {
          label: "Dispute Detail"
        },
        resolve: {
          label: "Resolution"
        }
      }
    },
    kpi_entry_line: {
      label: "Entry Line",
      pluralLabel: "Entry Lines",
      description: "One indicator's actual value, completion rate, score and calculation trace.",
      fields: {
        sheet: {
          label: "Entry Sheet"
        },
        plan_indicator: {
          label: "Source Assignment"
        },
        indicator: {
          label: "Indicator"
        },
        indicator_name: {
          label: "Indicator"
        },
        unit: {
          label: "Unit"
        },
        direction: {
          label: "Direction",
          options: {
            positive: "Higher is Better",
            negative: "Lower is Better"
          }
        },
        scoring_method: {
          label: "Scoring Method",
          options: {
            linear: "Linear",
            step: "Step",
            range: "Range Interpolation",
            formula: "Custom Formula"
          }
        },
        target_value: {
          label: "Target"
        },
        weight: {
          label: "Weight (%)"
        },
        actual_value: {
          label: "Actual"
        },
        completion_rate: {
          label: "Completion (%)"
        },
        score_rate: {
          label: "Score Rate (%)"
        },
        score: {
          label: "Score"
        },
        adjusted_score: {
          label: "Adjusted Score"
        },
        final_score: {
          label: "Final Score"
        },
        is_adjusted: {
          label: "Adjusted"
        },
        adjust_type_applied: {
          label: "Adjustment Type",
          options: {
            source: "Source Data (Actual Value)",
            result: "Computed Result (Score)"
          }
        },
        calc_trace: {
          label: "Calculation Trace"
        },
        last_adjustment: {
          label: "Latest Adjustment"
        },
        remark: {
          label: "Remark"
        }
      },
      _views: {
        default: {
          label: "Entry Line"
        },
        unfilled: {
          label: "Missing Actuals"
        }
      },
      _sections: {
        entry: {
          label: "Entry"
        }
      }
    },
    kpi_entry_sheet: {
      label: "Entry Sheet",
      pluralLabel: "Entry Sheets",
      description: "One subject's indicator entries and review history under one plan.",
      fields: {
        name: {
          label: "Sheet"
        },
        plan: {
          label: "Plan"
        },
        subject: {
          label: "Subject"
        },
        subject_type: {
          label: "Subject Type",
          options: {
            department: "HQ Department",
            branch: "Branch"
          }
        },
        status: {
          label: "Status",
          options: {
            draft: "Entering",
            submitted: "Submitted",
            branch_checking: "Under Branch Verification",
            hr_reviewing: "Under HR Review",
            leader_approving: "Under Executive Approval",
            approved: "Passed",
            archived: "Archived"
          }
        },
        current_step: {
          label: "Current Step No."
        },
        pending_action: {
          label: "Pending Action (written by buttons)",
          options: {
            submit: "Submit",
            approve: "Approve",
            reject: "Reject",
            archive: "Archive"
          }
        },
        action_reason: {
          label: "Action Reason / Comment"
        },
        last_reject_reason: {
          label: "Latest Rejection Reason"
        },
        submitted_at: {
          label: "Submitted At"
        },
        submitted_by: {
          label: "Submitted By"
        },
        approved_at: {
          label: "Final Approval At"
        },
        approved_by: {
          label: "Final Approver"
        },
        archived_at: {
          label: "Archived At"
        },
        line_count: {
          label: "Indicators"
        },
        weight_total: {
          label: "Total Weight (%)"
        },
        indicator_score: {
          label: "Indicator Score Total"
        },
        bonus_total: {
          label: "Bonus & Penalty Total"
        },
        total_score: {
          label: "Final Score"
        },
        remark: {
          label: "Entry Notes"
        }
      },
      _actions: {
        kpi_sheet_approve: {
          label: "Approve",
          successMessage: "Approved; the sheet moves to the next step.",
          params: {
            reason: {
              label: "Review Comment (optional)"
            }
          }
        },
        kpi_sheet_archive: {
          label: "Archive",
          confirmText: "Archiving generates an immutable snapshot and locks the data for good. Archive?",
          successMessage: "Archived; a snapshot has been generated."
        },
        kpi_sheet_reject: {
          label: "Reject",
          successMessage: "Rejected; the entry sheet returns to the previous step.",
          params: {
            reason: {
              label: "Rejection Reason"
            }
          }
        },
        kpi_sheet_submit: {
          label: "Submit Entry",
          confirmText: "Submitting freezes the entered data and starts verification and review. Submit?",
          successMessage: "Entry sheet submitted; it now enters verification and review."
        }
      },
      _views: {
        default: {
          label: "All Entry Sheets"
        },
        filling: {
          label: "Entering"
        },
        checking: {
          label: "Under Branch Verification"
        },
        hr: {
          label: "Awaiting HR Review"
        },
        leader: {
          label: "Awaiting Executive Approval"
        },
        approved: {
          label: "Passed"
        },
        archived: {
          label: "Archived"
        },
        board: {
          label: "Workflow Board"
        }
      },
      _sections: {
        head: {
          label: "Entry Sheet"
        },
        flow: {
          label: "Workflow"
        }
      }
    },
    kpi_indicator: {
      label: "Indicator",
      pluralLabel: "Indicators",
      description: "Indicator definition, data source and scoring rule, with a traceable version chain.",
      fields: {
        code: {
          label: "Code"
        },
        name: {
          label: "Name"
        },
        category: {
          label: "Category",
          options: {
            business: "Business Performance",
            management: "Management Effectiveness",
            service: "Service Quality",
            compliance: "Safety & Compliance",
            other: "Other"
          }
        },
        owner_unit: {
          label: "Department Segment"
        },
        data_source: {
          label: "Data Source",
          options: {
            manual: "Manual Entry",
            import: "Bulk Import",
            system: "System Computed"
          }
        },
        unit: {
          label: "Unit"
        },
        value_scale: {
          label: "Decimal Places"
        },
        direction: {
          label: "Direction",
          options: {
            positive: "Higher is Better",
            negative: "Lower is Better"
          }
        },
        scoring_method: {
          label: "Scoring Method",
          options: {
            linear: "Linear",
            step: "Step",
            range: "Range Interpolation",
            formula: "Custom Formula"
          }
        },
        cap_rate: {
          label: "Completion Cap (%)"
        },
        floor_rate: {
          label: "Completion Floor (%)"
        },
        range_lower_rate: {
          label: "Range Lower Completion (%)"
        },
        range_upper_rate: {
          label: "Range Upper Completion (%)"
        },
        score_formula: {
          label: "Scoring Formula"
        },
        description: {
          label: "Definition Notes"
        },
        status: {
          label: "Status",
          options: {
            active: "Active",
            retired: "Inactive"
          }
        },
        version_no: {
          label: "Version"
        },
        superseded_by: {
          label: "Superseded By"
        }
      },
      _views: {
        default: {
          label: "All Indicators"
        },
        active: {
          label: "Active Only"
        }
      },
      _sections: {
        basic: {
          label: "Basic Information"
        },
        scoring: {
          label: "Scoring Rule"
        },
        desc: {
          label: "Definition Notes"
        }
      }
    },
    kpi_indicator_step: {
      label: "Score Band",
      pluralLabel: "Score Band",
      description: "The completion-rate bands of the step scoring method and the score rate each yields.",
      fields: {
        indicator: {
          label: "Indicator"
        },
        seq: {
          label: "No."
        },
        label: {
          label: "Band Name"
        },
        min_rate: {
          label: "Completion Lower Bound (%, inclusive)"
        },
        max_rate: {
          label: "Completion Upper Bound (%, exclusive; blank = no upper bound)"
        },
        score_rate: {
          label: "Score Rate (%)"
        }
      },
      _views: {
        default: {
          label: "Score Band"
        }
      },
      _sections: {
        main: {
          label: "Score Band"
        }
      }
    },
    kpi_personal_item: {
      label: "Personal Item",
      pluralLabel: "Personal Item",
      description: "Specific indicators an employee carries personally, with weight and target.",
      fields: {
        assignment: {
          label: "Staff Assignment"
        },
        name: {
          label: "Item Name"
        },
        plan_indicator: {
          label: "Assigned Indicator"
        },
        weight: {
          label: "Item Weight (%)"
        },
        target_value: {
          label: "Personal Target"
        }
      },
      _views: {
        default: {
          label: "Personal Item"
        }
      },
      _sections: {
        main: {
          label: "Personal Item"
        }
      }
    },
    kpi_plan: {
      label: "Assessment Plan",
      pluralLabel: "Assessment Plans",
      description: "The full configuration of one assessment cycle: period, indicator assignments, assessment relationships, staff assignments and the review workflow.",
      fields: {
        name: {
          label: "Plan Name"
        },
        period_type: {
          label: "Period Type",
          options: {
            month: "Month",
            quarter: "Quarter",
            half_year: "Half-Year",
            year: "Year"
          }
        },
        year: {
          label: "Year"
        },
        period_no: {
          label: "Period No. (month / quarter / half-year)"
        },
        period_start: {
          label: "Period Start"
        },
        period_end: {
          label: "Period End"
        },
        version_no: {
          label: "Version"
        },
        status: {
          label: "Status",
          options: {
            draft: "Draft",
            published: "Published",
            closed: "Closed",
            archived: "Archived"
          }
        },
        based_on: {
          label: "Copy From Version"
        },
        published_at: {
          label: "Published At"
        },
        published_by: {
          label: "Published By"
        },
        description: {
          label: "Plan Notes"
        },
        subject_count: {
          label: "Participating Subjects"
        },
        indicator_count: {
          label: "Indicators Assigned"
        },
        open_dispute_count: {
          label: "Open Disputes"
        }
      },
      _actions: {
        kpi_plan_archive: {
          label: "Archive Plan",
          successMessage: "Plan archived."
        },
        kpi_plan_close: {
          label: "Close Plan",
          confirmText: "Once closed, no further entry or adjustment is accepted. Close this plan?",
          successMessage: "Plan closed."
        },
        kpi_plan_publish: {
          label: "Publish Plan",
          confirmText: "An integrity check runs first. Once it passes, the plan freezes and an entry sheet is generated for every participating subject. Publish?",
          successMessage: "Plan published; entry sheets have been generated."
        }
      },
      _views: {
        default: {
          label: "All Plans"
        },
        draft: {
          label: "Draft"
        },
        published: {
          label: "Published"
        },
        board: {
          label: "Status Board"
        }
      },
      _sections: {
        basic: {
          label: "Plan Information"
        },
        publish: {
          label: "Publication"
        }
      }
    },
    kpi_plan_indicator: {
      label: "Indicator Assignment",
      pluralLabel: "Indicator Assignment",
      description: "Assigns an indicator to a subject with a weight and a target value.",
      fields: {
        plan: {
          label: "Plan"
        },
        name: {
          label: "Assignment Name"
        },
        indicator: {
          label: "Indicator"
        },
        subject: {
          label: "Subject"
        },
        weight: {
          label: "Weight (%)"
        },
        target_value: {
          label: "Target Value"
        },
        baseline_value: {
          label: "Baseline (Previous Period)"
        },
        data_source: {
          label: "Data Source (overrides indicator default)",
          options: {
            inherit: "Inherit from Indicator",
            manual: "Manual Entry",
            import: "Bulk Import",
            system: "System Computed"
          }
        },
        dispute_status: {
          label: "Dispute Status",
          options: {
            none: "No Dispute",
            open: "In Dispute",
            resolved: "Resolved"
          }
        },
        remark: {
          label: "Remark"
        }
      },
      _views: {
        default: {
          label: "Indicator Assignment"
        },
        disputed: {
          label: "In Dispute"
        }
      },
      _sections: {
        main: {
          label: "Indicator Assignment"
        }
      }
    },
    kpi_plan_step: {
      label: "Workflow Step",
      pluralLabel: "Workflow Step",
      description: "The order of review steps in a plan and the position that reviews each.",
      fields: {
        plan: {
          label: "Plan"
        },
        seq: {
          label: "Order"
        },
        step_type: {
          label: "Step Type",
          options: {
            dept_submit: "Department Entry",
            branch_check: "Branch Verification (Parallel)",
            hr_review: "HR Review",
            leader_approve: "Executive Approval"
          }
        },
        label: {
          label: "Step Name"
        },
        approver_position: {
          label: "Review Position",
          options: {
            kpi_dept_reporter: "Department Reporter",
            kpi_branch_checker: "Branch Checker",
            kpi_hr_reviewer: "HR Review",
            kpi_hr_head: "HR Head",
            kpi_exec_leader: "Executive Leader"
          }
        }
      },
      _views: {
        default: {
          label: "Workflow Step"
        }
      },
      _sections: {
        main: {
          label: "Workflow Step"
        }
      }
    },
    kpi_plan_subject: {
      label: "Participating Subject",
      pluralLabel: "Participating Subject",
      description: "A plan's assessed subjects, owning departments, subject weights and executive leaders.",
      fields: {
        plan: {
          label: "Plan"
        },
        name: {
          label: "Subject Name"
        },
        subject: {
          label: "Subject"
        },
        subject_type: {
          label: "Subject Type",
          options: {
            department: "HQ Department",
            branch: "Branch"
          }
        },
        assessor_unit: {
          label: "Owning Department (sets the indicators)"
        },
        subject_weight: {
          label: "Subject Weight (%)"
        },
        leader: {
          label: "Executive Leader"
        },
        remark: {
          label: "Remark"
        }
      },
      _views: {
        default: {
          label: "Participating Subject"
        }
      },
      _sections: {
        main: {
          label: "Participating Subject"
        }
      }
    },
    kpi_result: {
      label: "Assessment Result",
      pluralLabel: "Assessment Results",
      description: "Scores and rankings aggregated across four dimensions: department, branch, person and executive leader.",
      fields: {
        name: {
          label: "Result Name"
        },
        plan: {
          label: "Assessment Plan"
        },
        dimension: {
          label: "Dimension",
          options: {
            department: "Department",
            branch: "Branch",
            person: "Person",
            leader: "Executive Leader"
          }
        },
        unit: {
          label: "Org Unit"
        },
        person: {
          label: "Person"
        },
        sheet: {
          label: "Source Entry Sheet"
        },
        score: {
          label: "Score"
        },
        weighted_score: {
          label: "Weighted Score"
        },
        rank: {
          label: "Rank"
        },
        breakdown: {
          label: "Calculation Breakdown"
        },
        generated_at: {
          label: "Generated At"
        }
      },
      _views: {
        default: {
          label: "Assessment Result"
        },
        department: {
          label: "Department"
        },
        branch: {
          label: "Branch"
        },
        person: {
          label: "Person"
        },
        leader: {
          label: "Executive Leader"
        }
      },
      _sections: {
        main: {
          label: "Assessment Result"
        }
      }
    },
    kpi_review_record: {
      label: "Review Record",
      pluralLabel: "Review Record",
      description: "An append-only trace of every workflow action on an entry sheet: who, when, from which status to which, and why.",
      fields: {
        name: {
          label: "Record No."
        },
        sheet: {
          label: "Entry Sheet"
        },
        action: {
          label: "Action",
          options: {
            generate: "Generated",
            submit: "Submit",
            confirm: "Confirm",
            dispute: "Raise Dispute",
            approve: "Approve",
            reject: "Reject",
            archive: "Archive",
            adjust: "Data Adjustment"
          }
        },
        step_label: {
          label: "Step"
        },
        from_status: {
          label: "From Status"
        },
        to_status: {
          label: "To Status"
        },
        actor: {
          label: "Actor"
        },
        reason: {
          label: "Reason / Comment"
        },
        acted_at: {
          label: "Time"
        }
      },
      _views: {
        default: {
          label: "Review Record"
        },
        rejects: {
          label: "Rejections"
        },
        timeline: {
          label: "Timeline"
        }
      },
      _sections: {
        main: {
          label: "Review Record"
        }
      }
    },
    kpi_snapshot: {
      label: "Archive Snapshot",
      pluralLabel: "Archive Snapshots",
      description: "The immutable record of an archived entry sheet — the authority for historical queries.",
      fields: {
        name: {
          label: "Snapshot Name"
        },
        plan: {
          label: "Assessment Plan"
        },
        sheet: {
          label: "Entry Sheet"
        },
        subject: {
          label: "Subject"
        },
        total_score: {
          label: "Final Score"
        },
        payload: {
          label: "Snapshot Payload"
        },
        checksum: {
          label: "Checksum"
        },
        archived_by: {
          label: "Archived By"
        },
        archived_at: {
          label: "Archived At"
        }
      },
      _views: {
        default: {
          label: "Archive Snapshot"
        }
      },
      _sections: {
        main: {
          label: "Archive Snapshot"
        }
      }
    },
    kpi_staff_assignment: {
      label: "Staff Assignment",
      pluralLabel: "Staff Assignment",
      description: "Which department segments an employee carries, with the weight and personal coefficient for each.",
      fields: {
        plan: {
          label: "Plan"
        },
        name: {
          label: "Staff Assignment Name"
        },
        employee: {
          label: "Employee"
        },
        unit: {
          label: "Department Segment"
        },
        weight: {
          label: "Assignment Weight (%)"
        },
        coefficient: {
          label: "Personal Coefficient"
        },
        remark: {
          label: "Remark"
        }
      },
      _views: {
        default: {
          label: "Staff Assignment"
        }
      },
      _sections: {
        main: {
          label: "Staff Assignment"
        }
      }
    }
  },
  apps: {
    kpi_app: {
      label: "KPI Assessment",
      navigation: {
        nav_home: {
          label: "Workbench"
        },
        group_entry: {
          label: "Entry & Review"
        },
        nav_sheets: {
          label: "Entry Sheet"
        },
        nav_my_checks: {
          label: "My Verifications"
        },
        nav_hr_queue: {
          label: "Awaiting HR Review"
        },
        nav_leader_queue: {
          label: "Awaiting Executive Approval"
        },
        nav_lines: {
          label: "Entry Line"
        },
        nav_checks: {
          label: "Branch Verification"
        },
        nav_bonus: {
          label: "Bonus & Penalty"
        },
        nav_adjust: {
          label: "Data Adjustment"
        },
        group_plan: {
          label: "Assessment Plan"
        },
        nav_plans: {
          label: "Plan Version"
        },
        nav_plan_indicators: {
          label: "Indicator Assignment"
        },
        nav_plan_subjects: {
          label: "Participating Subject"
        },
        nav_assignments: {
          label: "Staff Assignment"
        },
        nav_disputes: {
          label: "Indicator Dispute"
        },
        group_results: {
          label: "Results & Archive"
        },
        nav_dashboard: {
          label: "Results Board"
        },
        nav_results: {
          label: "Assessment Result"
        },
        nav_report_unit: {
          label: "Department × Dimension Matrix"
        },
        nav_report_person: {
          label: "Person Scores"
        },
        nav_report_line: {
          label: "Indicator Completion"
        },
        nav_snapshots: {
          label: "Archive Snapshot"
        },
        group_setup: {
          label: "Setup"
        },
        nav_indicators: {
          label: "Indicator Library"
        },
        nav_ops_dashboard: {
          label: "Workflow Progress"
        },
        group_audit: {
          label: "Audit"
        },
        nav_reviews: {
          label: "Review Record"
        }
      }
    }
  },
  dashboards: {
    kpi_progress_dashboard: {
      label: "Assessment Progress",
      description: "Where each entry sheet sits in the workflow, the spread of subject types, and average indicator completion.",
      widgets: {
        p_draft: {
          title: "Entering"
        },
        p_check: {
          title: "Under Branch Verification"
        },
        p_review: {
          title: "In Review"
        },
        p_done: {
          title: "Passed / Archived"
        },
        p_status: {
          title: "Entry Sheets by Status"
        },
        p_type: {
          title: "Average Indicator Score by Subject Type"
        },
        p_completion: {
          title: "Average Completion by Indicator (%)"
        }
      }
    },
    kpi_results_dashboard: {
      label: "Assessment Results Board",
      description: "An overview of scores across the department, branch, person and executive-leader dimensions, drillable to the detail.",
      widgets: {
        m_count: {
          title: "Results"
        },
        m_avg: {
          title: "Average Score"
        },
        m_max: {
          title: "Highest Score"
        },
        m_min: {
          title: "Lowest Score"
        },
        bar_unit: {
          title: "Average Score by Org Unit (Department / Branch)"
        },
        bar_person: {
          title: "Person Score"
        },
        tbl_dim: {
          title: "By Dimension"
        }
      }
    }
  },
  pages: {
    kpi_home: {
      label: "Workbench",
      title: "KPI Assessment",
      subtitle: "Indicator library → plan configuration → indicator assignment → entry → parallel verification → review → scoring → adjustment → aggregation → archive"
    }
  }
};
